name: gtrack-policy-v2
on:
  pull_request:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: require DEV_NOTES.md
        run: test -f docs/DEV_NOTES.md || (echo "docs/DEV_NOTES.md is required" && exit 1)

  guard-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Ensure PR body contains 'Docs updated' block (no API)
        shell: bash
        run: |
          set -euo pipefail
          body="$(jq -r '.pull_request.body // ""' "$GITHUB_EVENT_PATH")"
          if echo "$body" | grep -qi '^Docs updated'; then
            echo "OK: PR body contains 'Docs updated'."
          else
            echo "::error::PR body must start with 'Docs updated'"; exit 1
          fi

  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch naming (adapter)
        run: |
          BR="${{ github.head_ref }}"
          # allow bootstrap branches; warn only
          echo "Branch: $BR (naming check relaxed for bootstrap)"

  fresh-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp check (relaxed)
        run: echo "fresh-branch relaxed for bootstrap"
