name: gtrack-policy-v2
on:
  pull_request:
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: require DEV_NOTES.md
        run: test -f docs/DEV_NOTES.md || (echo "docs/DEV_NOTES.md is required" && exit 1)

  guard-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Ensure PR body contains 'Docs updated' only if docs/** changed (no API)
        shell: bash
        run: |
          set -euo pipefail
          BASE_SHA="$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")"
          HEAD_SHA="${GITHUB_SHA}"
          git diff --name-only "$BASE_SHA" "$HEAD_SHA" > changed.txt
          if ! grep -q '^docs/' changed.txt; then
            echo "No docs/ changes → skipping requirement."
            exit 0
          fi
          body="$(jq -r '.pull_request.body // ""' "$GITHUB_EVENT_PATH")"
          if echo "$body" | grep -qi 'Docs updated'; then
            echo "OK: PR body includes 'Docs updated'."
          else
            echo "::error::PR body must contain 'Docs updated' because docs/ changed."; \
            echo "Changed docs files:"; grep '^docs/' changed.txt || true; exit 1
          fi

  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: relaxed naming (bootstrap)
        run: echo "relaxed"

  fresh-branch:
    runs-on: ubuntu-latest
    steps:
      - name: relaxed freshness (bootstrap)
        run: echo "relaxed"
