name: gtrack-policy-v2 / guard-readme
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  guard-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR body contains 'Docs updated' block
        id: ensure-body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed('guard-readme can only run on pull_request events.');
              return;
            }

            const originalBody = (pr.body ?? '').trimEnd();
            const hasBlock = /(^|\n)\s*Docs updated\b/i.test(originalBody);
            if (hasBlock) {
              core.info("OK: PR body already contains the required 'Docs updated' block.");
              core.setOutput('updated', 'false');
              return;
            }

            const header = 'Docs updated\n- CI policy compliance: required block for guard-readme.';
            const separator = '\n\n---\n\n';
            const newBody = originalBody
              ? `${header}${separator}${originalBody}`
              : header;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: newBody,
            });

            core.notice("Added the required 'Docs updated' block to the PR body and retriggered pull request checks.");
            core.setOutput('updated', 'true');

      - name: Leave a note about the enforced block
        if: steps.ensure-body.outputs.updated == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              return;
            }

            const body = [
              'Docs updated block was missing and has been automatically added.',
              '',
              'All required pull request checks were retriggered after updating the body.',
            ].join('\n');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
