name: gtrack-policy-v2 / guard-readme
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  guard-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR body contains 'Docs updated' block
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request?.body || "").trim();
            if (/docs updated/i.test(body)) {
              core.info("OK: PR body contains 'Docs updated'.");
            } else {
              core.setFailed("PR body must contain 'Docs updated' block");
            }
